provision {
  connection {
    url = "jdbc:snowflake://LOVES-LOVES_DEVELOPMENT.snowflakecomputing.com"
    properties {
      user = ${SNOWFLAKE_USER}
      role = ${SNOWFLAKE_ROLE}
      warehouse = ${SNOWFLAKE_WAREHOUSE}
      private_key_file = ${SNOWFLAKE_PRIVATE_KEY_FILE}
      private_key_file_pwd = ${SNOWFLAKE_PRIVATE_KEY_PASSPHRASE}
    }
  }

  metadata {
    database = SFADMIN_PROVISION_DB
    schema = provision
    statementTable = statements
  }

  owner {
    role = SECURITYADMIN
    user = SECURITYADMIN
    networkRule = ACCOUNTADMIN
    networkPolicy = SECURITYADMIN
    tag = ACCOUNTADMIN
    monitor = ACCOUNTADMIN
    default = DATA_ADMINS
  }

  validation { entryDepthLimitAction = disabled }
  threads = 16
  enableCache = true
  maxDestroys = 200
  userDestroyType = DISABLE
}

sql.provision {
  # keep noise down
  excludeObjectTypes = [ "MATERIALIZED VIEW", "ROW ACCESS POLICY", "AGGREGATION POLICY" ]
}
